# Generated by Django 5.2.17 on 2026-09-20 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
            ],
            options={
                'verbose_name': 'música',
                'verbose_name_plural': 'músicas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PedidoMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ouvinte', models.CharField(max_length=100, verbose_name='nome')),
                ('localidade', models.CharField(max_length=120, verbose_name='localidade')),
                ('tipo_contato', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'E-mail')], max_length=10, verbose_name='tipo de contato')),
                ('contato', models.CharField(max_length=150, verbose_name='telefone ou e-mail')),
                ('mensagem', models.TextField(blank=True)),
                ('aceita_politica', models.BooleanField(verbose_name='aceitou a política de privacidade')),
                ('confirma_dados', models.BooleanField(verbose_name='confirmou os dados')),
                ('aceita_condicoes', models.BooleanField(verbose_name='aceitou as condições')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='radio.musica', verbose_name='música')),
            ],
            options={
                'verbose_name': 'pedido musical',
                'verbose_name_plural': 'pedidos musicais',
                'ordering': ['-data'],
            },
        ),
    ]
